#!/usr/bin/env python3
"""Author Chapter VIII (Defensive Driving) content.

Written as a builder rather than raw JSON only to avoid repeating the long
sourceDocument string on every one of ~60 source refs. Every quote below was read
from source_material/chapters/CH_VIII_Defensive_Driving.txt and is checked verbatim
against the PDF by tools/validate_content.py.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "app/src/content/data/parts/ch_VIII.json"
SD = ("West Virginia Driver's Licensing Handbook (Rev. 07/2026, retrieved 2026-09-14, "
      "SHA-256 45082246ab6df6c75d0968a680b6a7ad26d334aeb2e547871dea3fd7c7828a7a)")


def S(section, pdf, quote):
    return {"sourceDocument": SD, "chapter": "VIII", "chapterTitle": "Defensive Driving",
            "section": section, "pdfPage": pdf, "printedPage": pdf - 10,
            "sourceQuote": quote, "verifiedDate": "2026-09-14"}


topics = [
    {"id": "driving-habits", "title": "Good and Bad Driving Habits", "chapter": "VIII",
     "order": 80, "blurb": "The five habits the handbook names as causes of crashes — and what to do instead.",
     "examWeight": 1.0},
    {"id": "light-and-night", "title": "Light Conditions and Night Driving", "chapter": "VIII",
     "order": 81, "blurb": "Headlight law, dimming distances, glare, and overdriving your headlights.",
     "examWeight": 1.3},
    {"id": "bad-weather", "title": "Rain, Snow, Fog and Flooding", "chapter": "VIII",
     "order": 82, "blurb": "Hydroplaning, wet pavement, ice, fog, and why you never drive into water.",
     "examWeight": 1.4},
    {"id": "vehicle-driver-condition", "title": "Vehicle and Driver Condition", "chapter": "VIII",
     "order": 83, "blurb": "WV inspection law, common defects, fatigue and emotional state.",
     "examWeight": 1.0},
    {"id": "traffic-situations", "title": "Traffic Situations and Passing", "chapter": "VIII",
     "order": 84, "blurb": "The six positions another vehicle can take before a crash, and passing safely.",
     "examWeight": 1.2},
]

concepts = [
    ("c-bad-habits", "driving-habits", "The five bad driving habits",
     "Bad driving habits result from laziness, impatience, inattention, arrogance and aggressiveness.",
     S("Bad Driving Habits", 71, "Bad driving habits result from laziness, impatience, inattention,")),
    ("c-turn-head", "driving-habits", "Turn your head, don't just use mirrors",
     "Always turn your head and look behind you for traffic before changing lanes, pulling from the curb or opening your door.",
     S("Laziness", 71, "Always turn your head and look behind you")),
    ("c-signal-always", "driving-habits", "Always signal your intention",
     "Always signal before turning, changing lanes, or driving away from the curb.",
     S("Laziness", 71, "Always signal your intention before turning, changing")),
    ("c-complete-stop", "driving-habits", "A complete stop is required",
     "You must come to a complete stop at a stop sign or red light regardless of traffic, even when making a right turn.",
     S("Impatience", 71, "a complete stop at a stop sign or red light,")),
    ("c-concentration", "driving-habits", "Driving is a full-time job",
     "The driver's seat is no place for daydreaming, window shopping or distracting conversation.",
     S("Concentration", 72, "of concentration can result in a driver's failure to be observant enough to avoid a crash.")),

    ("c-dim-meeting", "light-and-night", "Dim within 500 feet when meeting",
     "Dim your headlight beams within 500 feet of an oncoming vehicle.",
     S("Light Conditions", 72, "dim your headlight beams within 500")),
    ("c-dim-following", "light-and-night", "Dim within 200 feet when following",
     "Dim your headlights within 200 feet of a vehicle you are following.",
     S("Light Conditions", 72, "dim your headlights within 200 feet of the")),
    ("c-overdrive", "light-and-night", "Overdriving your headlights",
     "Overdriving your headlights means driving too fast to stop safely within the distance clearly lit by them.",
     S("Light Conditions", 72, "means driving too fast to stop safely within the distance clearly lit by your")),
    ("c-glare", "light-and-night", "Oncoming headlight glare",
     "Looking directly into oncoming headlights causes momentary blindness; slow down, keep right and look at the right edge of the road.",
     S("Light Conditions", 72, "Looking directly into oncoming headlights causes momentary blindness.")),
    ("c-headlights-law", "light-and-night", "Headlights, not parking lights",
     "Turn on headlights rather than parking lights when it begins to get dark or whenever visibility may be impaired.",
     S("Light Conditions", 72, "It is the law and a good idea to turn on your headlights, not just your parking")),

    ("c-wet-start", "bad-weather", "The start of a light rain is worst",
     "At the start of a light rain, oil, dirt and water form a slippery film that increases stopping distance.",
     S("Rain", 73, "a mixture of oil, dirt, and water form a slippery film on the road.")),
    ("c-hydroplane", "bad-weather", "Hydroplaning speeds",
     "Partial hydroplaning begins around 35 mph, and at 55 mph tires can ride entirely on top of the water.",
     S("Hydroplaning", 73, "partial hydroplaning occurs on the road at about 35 mph.")),
    ("c-hydroplane-prevent", "bad-weather", "Preventing hydroplaning",
     "Slow down in rain, keep tires properly inflated, and replace tires when tread wear indicators are visible.",
     S("Hydroplaning", 73, "Keep tires properly inflated.")),
    ("c-flood-never", "bad-weather", "Never drive into flood water",
     "Never attempt to drive across a flooded roadway.",
     S("Flooding", 73, "Never attempt to drive across a flooded roadway.")),
    ("c-flood-depth", "bad-weather", "How little water it takes",
     "As little as six inches of water can float some smaller vehicles, and two feet will carry most away.",
     S("Flooding", 73, "As little as six (6) inches of water can float some smaller vehicles, while two")),
    ("c-ice-brake", "bad-weather", "Braking on ice and snow",
     "On ice or packed snow apply the brakes gently and smoothly, releasing at the first hint the wheels are slipping.",
     S("Snow and Ice", 74, "always apply the brakes gently and smoothly.")),
    ("c-abs", "bad-weather", "Anti-lock brakes and steering",
     "With anti-lock brakes you keep the ability to steer while braking; without them you cannot steer unless you pump the brakes.",
     S("Snow and Ice", 74, "In a vehicle equipped with anti-lock brakes, you maintain the ability to steer while braking.")),
    ("c-fog", "bad-weather", "Driving in fog or smoke",
     "In fog or dense smoke, reduce speed, be prepared for an emergency stop, and use low-beam headlights.",
     S("Fog and Smoke", 74, "Use your low-beam headlights.")),

    ("c-inspection", "vehicle-driver-condition", "WV inspection every two years",
     "West Virginia requires an inspection of all vehicles every two years, and removing the inspection sticker is against the law.",
     S("Vehicle Conditions (State Inspection Law)", 74,
       "West Virginia requires an")),
    ("c-defects", "vehicle-driver-condition", "Common defects that cause crashes",
     "Common vehicle defects that cause crashes include faulty tires, brakes, lights, wipers, defrosters, exhaust, horn, mirrors and unusable seat belts.",
     S("Vehicle Conditions (State Inspection Law)", 75,
       "Common vehicle defects that cause crashes are faulty tires, brakes, lights, windshield wipers, defrosters")),
    ("c-fatigue-break", "vehicle-driver-condition", "Rest breaks on long trips",
     "On a long trip take a 10-minute rest break at least every two hours, spent outside the vehicle.",
     S("Fatigue", 75, "take a 10-minute rest break at least every two (2) hours.")),
    ("c-fatigue-effect", "vehicle-driver-condition", "What fatigue does",
     "Being tired dulls your mind and slows your reaction time.",
     S("Fatigue", 75, "Being tired dulls your mind and slows your reaction time.")),
    ("c-emotions", "vehicle-driver-condition", "Emotional state before driving",
     "Gain self control over anger, worry or fear before driving.",
     S("Emotional States", 75, "control these emotions and gain self control before driving.")),

    ("c-following-ahead", "traffic-situations", "The vehicle ahead may stop suddenly",
     "Always assume the vehicle ahead may stop suddenly and without warning, and keep a safe following distance.",
     S("Traffic Situations", 76, "the vehicle ahead of you may stop suddenly and without")),
    ("c-being-passed", "traffic-situations", "When another vehicle passes you",
     "Do not treat being passed as a challenge: slow down, keep as close to the right as possible and make it easier for them to pass.",
     S("Traffic Situations", 76, "slow down, and keep as close to the right side of the road as possible, making")),
    ("c-passing-speed", "traffic-situations", "Speeding to pass is illegal",
     "Exceeding the speed limit when passing is illegal; if you have to speed to pass, you probably do not need to pass.",
     S("Traffic Situations", 76, "Exceeding the speed limit when passing is")),
    ("c-tailgater", "traffic-situations", "Your duty to the driver behind",
     "You have a responsibility to the driver following you to signal whenever you change your driving pattern.",
     S("Traffic Situations", 76, "have a responsibility to the driver following you to signal whenever you make a change in your driving")),
]

lessons = [
    {"id": "l-driving-habits", "topicId": "driving-habits",
     "title": "The Habits That Cause Crashes",
     "rules": [
         {"text": "Bad driving habits result from laziness, impatience, inattention, arrogance and aggressiveness.",
          "source": S("Bad Driving Habits", 71,
                      "Bad driving habits result from laziness, impatience, inattention,")},
         {"text": "Always turn your head and look behind you before changing lanes, pulling out, or getting out on the traffic side.",
          "source": S("Laziness", 71, "Always turn your head and look behind you")},
         {"text": "Come to a complete stop at a stop sign or red light regardless of traffic, even when turning right.",
          "source": S("Impatience", 71, "a complete stop at a stop sign or red light,")},
     ],
     "plainEnglish": "The handbook names five specific habits: laziness, impatience, inattention, arrogance and aggressiveness. Laziness is checking only the mirror instead of turning your head, and not bothering to signal. Impatience is rolling a stop sign because nothing is coming and someone is behind you. Inattention is letting your grip and your focus loosen until the car wanders with your mind. Arrogance is treating the car as an extension of your ego.",
     "whyItMatters": "None of these are dramatic. They are all small, comfortable shortcuts that feel harmless every time you take them, which is exactly why they turn into habits. The handbook's point is that you have to notice them in yourself and correct them deliberately.",
     "example": "You approach a red light intending to turn right. Nothing is coming and the car behind is close. Slowing to 5 mph and rolling through feels safe and considerate. It is still a failure to stop, and it is the habit that will eventually meet a pedestrian stepping off the kerb you did not check for.",
     "conceptIds": ["c-bad-habits", "c-turn-head", "c-signal-always", "c-complete-stop", "c-concentration"],
     "estimatedMinutes": 5},

    {"id": "l-light-night", "topicId": "light-and-night",
     "title": "Seeing and Being Seen",
     "rules": [
         {"text": "Dim your headlight beams within 500 feet of an oncoming vehicle, and within 200 feet of a vehicle you are following.",
          "source": S("Light Conditions", 72, "dim your headlight beams within 500")},
         {"text": "Turn on headlights, not just parking lights, when it begins to get dark or whenever visibility may be impaired.",
          "source": S("Light Conditions", 72,
                      "It is the law and a good idea to turn on your headlights, not just your parking")},
         {"text": "Overdriving your headlights means driving too fast to stop within the distance they light.",
          "source": S("Light Conditions", 72,
                      "means driving too fast to stop safely within the distance clearly lit by your")},
     ],
     "plainEnglish": "Two numbers matter here and they are easy to mix up: 500 feet when you are meeting someone head-on, 200 feet when you are behind them. The bigger distance goes with the bigger risk — blinding an oncoming driver puts two cars in danger. Overdriving your headlights is the subtler idea: if your lights show 200 feet of road but you need 250 feet to stop, you are driving into a space you cannot see.",
     "whyItMatters": "At night your stopping distance does not shrink, but your seeing distance does. Most drivers never adjust speed for that. And if oncoming headlights do catch you, the handbook's instruction is specific: slow down, keep right, and look at the right edge of the road rather than into the lights.",
     "example": "On an unlit road at 55 mph you meet a car. You dim at about a football field and a half away, and as it passes you fix your eyes on the white line at the right edge rather than the glare, so you keep your lane and your night vision.",
     "conceptIds": ["c-dim-meeting", "c-dim-following", "c-overdrive", "c-glare", "c-headlights-law"],
     "estimatedMinutes": 6},

    {"id": "l-bad-weather", "topicId": "bad-weather",
     "title": "Rain, Ice, Fog and Standing Water",
     "rules": [
         {"text": "Partial hydroplaning begins at about 35 mph; at 55 mph tires can ride entirely on top of the water with no friction to brake, accelerate or corner.",
          "source": S("Hydroplaning", 73, "partial hydroplaning occurs on the road at about 35 mph.")},
         {"text": "Never attempt to drive across a flooded roadway. Six inches of water can float a small vehicle; two feet will carry most away.",
          "source": S("Flooding", 73,
                      "As little as six (6) inches of water can float some smaller vehicles, while two")},
         {"text": "In fog or dense smoke, reduce speed and use low-beam headlights.",
          "source": S("Fog and Smoke", 74, "Use your low-beam headlights.")},
     ],
     "plainEnglish": "Rain is most dangerous when it starts, because oil and dirt lift off the surface into a slippery film before the rain washes it away. As speed rises, the tires stop cutting through water and start riding on it — around 35 mph partially, and by 55 mph potentially not touching the road at all. When that happens you have no braking, no acceleration and no steering. In fog, low beams are correct: high beams reflect off the fog straight back at you.",
     "whyItMatters": "Flooded roads deserve their own warning. Nearly half of all flash flood deaths in the United States are motorists trapped in vehicles, and in many cases the road itself has already washed away under the water. Six inches is less than the depth of a kerb.",
     "example": "A back road has water running across it after a storm. It looks shallow. You cannot see the surface underneath, you do not know whether the road is still there, and six inches is enough to float the car. You turn around.",
     "conceptIds": ["c-wet-start", "c-hydroplane", "c-hydroplane-prevent", "c-flood-never",
                    "c-flood-depth", "c-ice-brake", "c-abs", "c-fog"],
     "estimatedMinutes": 8},

    {"id": "l-vehicle-driver", "topicId": "vehicle-driver-condition",
     "title": "Is the Car Fit, and Are You?",
     "rules": [
         {"text": "West Virginia requires an inspection of all vehicles every two years, and it is against the law to remove the inspection sticker.",
          "source": S("Vehicle Conditions (State Inspection Law)", 74, "West Virginia requires an")},
         {"text": "On a long trip take a 10-minute rest break at least every two hours, spent outside the vehicle.",
          "source": S("Fatigue", 75, "take a 10-minute rest break at least every two (2) hours.")},
         {"text": "Gain self control over anger, worry or fear before driving.",
          "source": S("Emotional States", 75, "control these emotions and gain self control before driving.")},
     ],
     "plainEnglish": "The handbook's line is blunt: you cannot safely drive 10 feet or 10 miles in an unsafe vehicle. West Virginia backs that with a two-yearly inspection and a windscreen sticker you are not allowed to remove. On the driver's side, the four conditions named are fatigue, alcohol, emotional state, and defective eyesight or hearing — and fatigue gets a specific remedy: stop every two hours for ten minutes, out of the car.",
     "whyItMatters": "Emotional state is the one people dismiss. Driving straight after a row, in tears or in a rage, is treated by the handbook as a condition affecting safe operation in the same list as alcohol and fatigue.",
     "example": "Three hours into a drive you notice you have stopped checking mirrors and cannot remember the last few miles. That is the point the handbook's two-hour rule was meant to catch. You pull in, get out, walk around for ten minutes.",
     "conceptIds": ["c-inspection", "c-defects", "c-fatigue-break", "c-fatigue-effect", "c-emotions"],
     "estimatedMinutes": 5},

    {"id": "l-traffic-situations", "topicId": "traffic-situations",
     "title": "Six Ways Another Vehicle Can Put You in a Crash",
     "rules": [
         {"text": "Assume the vehicle ahead may stop suddenly and without warning; keep a safe following distance.",
          "source": S("Traffic Situations", 76, "the vehicle ahead of you may stop suddenly and without")},
         {"text": "Do not treat being passed as a challenge. Slow down and keep as far right as practical.",
          "source": S("Traffic Situations", 76,
                      "slow down, and keep as close to the right side of the road as possible, making")},
         {"text": "Exceeding the speed limit when passing is illegal.",
          "source": S("Traffic Situations", 76, "Exceeding the speed limit when passing is")},
     ],
     "plainEnglish": "The handbook lists six positions another vehicle can be in before a crash: ahead of you, tailgating you, oncoming, at an angle, passing you, and being passed by you. Each has its own defence. The one people get wrong most often is being passed — treating it as a challenge instead of easing off and letting it happen causes sideswipes and run-off-road crashes.",
     "whyItMatters": "Note the handbook's test for passing: if you have to speed to pass, you probably do not need to pass. Exceeding the limit to overtake is illegal, so a pass that only works above the limit is not a legal pass.",
     "example": "Someone comes up fast behind you on a two-lane road and pulls out to pass. Rather than holding your speed, you ease off slightly and move right within your lane, which shortens the time they spend on the wrong side of the road.",
     "conceptIds": ["c-following-ahead", "c-being-passed", "c-passing-speed", "c-tailgater"],
     "estimatedMinutes": 5},
]


def Q(qid, topic, sub, concept, question, choices, correct, expl, qtype, diff, src):
    return {"id": qid, "topicId": topic, "subtopic": sub, "conceptId": concept,
            "question": question, "choices": choices, "correctAnswer": correct,
            "explanation": expl, "questionType": qtype, "difficulty": diff, "source": src}


questions = [
    Q("q-vh-001", "driving-habits", "Bad habits", "c-bad-habits",
      "Which five bad driving habits does the handbook identify?",
      ["Laziness, impatience, inattention, arrogance and aggressiveness",
       "Speeding, tailgating, drinking, texting and fatigue",
       "Inexperience, poor eyesight, slow reactions, nerves and distraction",
       "Braking late, steering roughly, poor parking, stalling and drifting"],
      0,
      "The handbook names these five specifically as the sources of bad driving habits, and asks you to evaluate your own behaviour against them. They are attitudes rather than manoeuvres, which is why they produce many different errors.",
      "direct", "core", S("Bad Driving Habits", 71,
                          "Bad driving habits result from laziness, impatience, inattention,")),

    Q("q-vh-002", "driving-habits", "Bad habits", "c-bad-habits",
      "A driver weaves in and out of traffic, speeds from stop to stop and tailgates. Which habit does the handbook describe?",
      ["Impatience", "Laziness", "Inattention", "Defensive driving"],
      0,
      "The handbook describes the impatient driver as one who speeds from stop to stop, weaves in and out of traffic and often tailgates. It notes such a driver may be concentrating hard, yet still disrupts traffic and raises the chance of causing a crash.",
      "scenario", "moderate", S("Impatience", 71,
                                "An impatient driver speeds from stop to")),

    Q("q-vh-003", "driving-habits", "Looking behind", "c-turn-head",
      "Before changing lanes, what does the handbook say you must do?",
      ["Turn your head and look behind you, not rely on the mirror alone",
       "Check the rear view mirror only",
       "Sound your horn and move over",
       "Rely on the blind spot monitor if fitted"],
      0,
      "The handbook warns specifically against becoming lazy and looking only in the rear view mirror. You are taught to look for other traffic before changing lanes, driving away from the curb, or getting out on the traffic side — and that means turning your head.",
      "direct", "core", S("Laziness", 71, "Always turn your head and look behind you")),

    Q("q-vh-004", "driving-habits", "Looking behind", "c-turn-head",
      "Which situation does the handbook say requires looking behind you for traffic?",
      ["Changing lanes, driving away from the curb, or getting out on the traffic side",
       "Only changing lanes on a highway",
       "Only when reversing out of a parking space",
       "Only when a passenger is in the vehicle"],
      0,
      "All three are listed together in the handbook. Opening your door into traffic is included because a door opened without looking is a common cause of collisions with cyclists and passing vehicles.",
      "reversed", "moderate", S("Laziness", 71,
                                "drive away from the curb, or get out of your vehicle on the traffic side.")),

    Q("q-vh-005", "driving-habits", "Signalling", "c-signal-always",
      "When does the handbook say you should signal?",
      ["Before turning, changing lanes, or driving away from the curb",
       "Only before turning at an intersection",
       "Only when another vehicle is visible behind you",
       "Only when changing lanes on a multi-lane road"],
      0,
      "The handbook says to always signal your intention before turning, changing lanes, or driving away from the curb, and calls failing to signal a bad habit related to laziness. Combining it with not looking behind could cause a serious crash.",
      "direct", "core", S("Laziness", 71,
                          "Always signal your intention before turning, changing")),

    Q("q-vh-006", "driving-habits", "Signalling", "c-tailgater",
      "Why does the handbook say you owe a signal to the driver behind you?",
      ["Because what you do affects them, especially if you slow or stop suddenly",
       "Because they cannot see your brake lights in daylight",
       "Because signalling is only legally required when followed",
       "Because it allows them to pass you safely"],
      0,
      "In the tailgating vehicle situation the handbook says you have a responsibility to the driver following you to signal whenever you make a change in your driving pattern, precisely because sudden slowing or stopping affects them most.",
      "application", "moderate", S("Traffic Situations", 76,
                                   "have a responsibility to the driver following you to signal whenever you make a change in your driving")),

    Q("q-vh-007", "driving-habits", "Stopping", "c-complete-stop",
      "You are turning right on red and no cross traffic is coming. What is required?",
      ["A complete stop, regardless of traffic",
       "A rolling stop is acceptable if the way is clear",
       "Slowing to walking pace is sufficient",
       "No stop is needed when turning right"],
      0,
      "The handbook states you must come to a complete stop at a stop sign or red light regardless of traffic, even when making a right turn. It specifically warns that pressure from following vehicles and the absence of cross traffic may tempt you to only slow down.",
      "scenario", "core", S("Impatience", 71, "a complete stop at a stop sign or red light,")),

    Q("q-vh-008", "driving-habits", "Concentration", "c-concentration",
      "How does the handbook describe the task of driving?",
      ["A full-time job with no room for daydreaming or distracting conversation",
       "A task that becomes automatic with experience",
       "Safe to combine with light conversation and scenery watching",
       "Demanding only in heavy traffic"],
      0,
      "The handbook says the driver's seat is no place for daydreaming, mental napping, window shopping, scenic viewing or distracting conversation, and concludes that driving an automobile is a full-time job. Lack of concentration means failing to be observant enough to avoid a crash.",
      "direct", "moderate", S("Concentration", 72,
                              "for daydreaming,  mental napping, window shopping, scenic viewing, or distracting conversation.")),

    Q("q-lt-001", "light-and-night", "Dimming", "c-dim-meeting",
      "Within what distance must you dim your headlights for an oncoming vehicle?",
      ["500 feet", "200 feet", "100 feet", "1,000 feet"],
      0,
      "The handbook requires dimming within 500 feet of an oncoming vehicle. The larger distance applies here because high beams aimed at a driver coming towards you cause momentary blindness while both vehicles are closing at speed.",
      "direct", "core", S("Light Conditions", 72, "dim your headlight beams within 500")),

    Q("q-lt-002", "light-and-night", "Dimming", "c-dim-following",
      "Within what distance must you dim your headlights when following another vehicle?",
      ["200 feet", "500 feet", "50 feet", "300 feet"],
      0,
      "When following, the handbook requires dimming within 200 feet. Your high beams reflect from the vehicle's mirrors straight into the other driver's eyes, so the rule applies even though you are behind them.",
      "direct", "core", S("Light Conditions", 72, "dim your headlights within 200 feet of the")),

    Q("q-lt-003", "light-and-night", "Dimming", "c-dim-meeting",
      "Which pairing of headlight dimming distances is correct?",
      ["500 feet when meeting, 200 feet when following",
       "200 feet when meeting, 500 feet when following",
       "500 feet in both cases",
       "200 feet in both cases"],
      0,
      "Meeting takes the larger figure of 500 feet, following the smaller 200 feet. A useful way to keep them straight: the head-on case is the more dangerous one, so it gets the bigger margin.",
      "reversed", "tricky", S("Light Conditions", 72,
                              "When following  another vehicle, dim your headlights within 200 feet of the")),

    Q("q-lt-004", "light-and-night", "Overdriving", "c-overdrive",
      "What does 'overdriving your headlights' mean?",
      ["Driving too fast to stop safely within the distance your headlights light up",
       "Using high beams when low beams would do",
       "Leaving headlights on during daylight",
       "Fitting headlights brighter than the law allows"],
      0,
      "The handbook defines it exactly this way. If your lights show 200 feet of road but you need more than that to stop, you are effectively driving blind into the space beyond them — the fix is to slow down at night, not to fit brighter bulbs.",
      "direct", "moderate", S("Light Conditions", 72,
                              "means driving too fast to stop safely within the distance clearly lit by your")),

    Q("q-lt-005", "light-and-night", "Overdriving", "c-overdrive",
      "On an unlit road at night your low beams light about 150 feet ahead, but stopping from your current speed takes about 200 feet. What should you do?",
      ["Slow down, because you are overdriving your headlights",
       "Maintain speed, since headlights do not affect braking",
       "Switch to parking lights to reduce glare",
       "Speed up to shorten your time in the dark"],
      0,
      "This is overdriving your headlights: you cannot stop within the distance you can see. The handbook's remedy is speed, because your stopping distance is fixed by physics while your seeing distance at night is fixed by your lights.",
      "application", "tricky", S("Light Conditions", 72,
                                 "A common term associated with light conditions that cause crashes is")),

    Q("q-lt-006", "light-and-night", "Glare", "c-glare",
      "An oncoming vehicle's headlights are dazzling you at night. Where should you look?",
      ["Well in front of your vehicle at the right edge of the road",
       "Directly at the oncoming headlights to judge distance",
       "At your own dashboard until the vehicle passes",
       "At the centre line to hold your position"],
      0,
      "Looking directly into oncoming headlights causes momentary blindness. The handbook says to slow down, keep to the right of your traffic lane, and look well in front of your vehicle at the right edge of the road — which keeps you positioned while preserving your night vision.",
      "scenario", "core", S("Light Conditions", 72,
                            "at night, slow down, keep to the right of your traffi  c lane, and look well in front of your vehicle at the")),

    Q("q-lt-007", "light-and-night", "Headlight law", "c-headlights-law",
      "When it begins to get dark, which lights does the handbook say to use?",
      ["Headlights, not just parking lights",
       "Parking lights until full darkness",
       "Hazard lights until full darkness",
       "Fog lights only"],
      0,
      "The handbook says it is both the law and a good idea to turn on your headlights, not just your parking lights, when it begins to get dark or any time visibility may be impaired by fog, smoke or extreme cloudiness. Turning them on a little early helps others see you.",
      "direct", "core", S("Light Conditions", 72,
                          "It is the law and a good idea to turn on your headlights, not just your parking")),

    Q("q-wx-001", "bad-weather", "Wet pavement", "c-wet-start",
      "When is rain generally most dangerous for traction?",
      ["At the start of a light rain, when oil, dirt and water form a slippery film",
       "After several hours of heavy rain",
       "Once the rain has stopped and the road is drying",
       "Only when the temperature is near freezing"],
      0,
      "The handbook singles out the start of a light rain, when a mixture of oil, dirt and water forms a slippery film on the road. Heavier rain later washes that film away. The condition makes it harder to keep contact on curves and increases stopping distance.",
      "direct", "moderate", S("Rain", 73,
                              "a mixture of oil, dirt, and water form a slippery film on the road.")),

    Q("q-wx-002", "bad-weather", "Hydroplaning", "c-hydroplane",
      "At approximately what speed does partial hydroplaning begin in a standard passenger vehicle?",
      ["About 35 mph", "About 15 mph", "About 55 mph", "About 70 mph"],
      0,
      "The handbook states that up to about 35 mph most tires wipe the road like a windshield wiper, and that partial hydroplaning occurs at about 35 mph. By 55 mph the tires can ride entirely on top of the water.",
      "direct", "moderate", S("Hydroplaning", 73,
                              "partial hydroplaning occurs on the road at about 35 mph.")),

    Q("q-wx-003", "bad-weather", "Hydroplaning", "c-hydroplane",
      "In a severe rainstorm at 55 mph, what does the handbook say happens?",
      ["Tires lose all contact with the road, leaving no friction to brake, accelerate or corner",
       "Tires grip normally as long as tread is good",
       "Braking distance doubles but steering is unaffected",
       "Hydroplaning cannot occur above 50 mph"],
      0,
      "At 55 mph in a severe rainstorm the handbook says tires lose all contact with the road and there is no friction available to brake, accelerate or corner. A gust of wind, a curve or a slight turn can then create an uncontrollable skid.",
      "scenario", "tricky", S("Hydroplaning", 73,
                              "In a severe rainstorm, tires lose all contact with the road at 55 mph.")),

    Q("q-wx-004", "bad-weather", "Hydroplaning", "c-hydroplane-prevent",
      "Which measure does the handbook recommend to reduce the possibility of hydroplaning?",
      ["Slow down and keep tires properly inflated, replacing them when tread wear indicators show",
       "Increase speed to cut through the water",
       "Brake firmly at the first sign of water",
       "Let air out of the tires for a wider contact patch"],
      0,
      "The handbook lists slowing down in rainstorms, on slushy roads or in standing water, and keeping tires properly inflated with adequate tread. Deep treads let water escape from under the tire and can prevent complete hydroplaning at normal highway speeds.",
      "direct", "core", S("Hydroplaning", 73, "Keep tires properly inflated.")),

    Q("q-wx-005", "bad-weather", "Flooding", "c-flood-never",
      "You come to a roadway covered by flowing water. What does the handbook instruct?",
      ["Never attempt to drive across a flooded roadway",
       "Cross slowly in a low gear if the water looks under a foot deep",
       "Cross quickly to avoid stalling",
       "Follow another vehicle across to test the depth"],
      0,
      "The instruction is absolute: never attempt to drive across a flooded roadway. The handbook notes that in many cases victims drive directly off the edge of an eroded road without knowing the road is no longer there.",
      "scenario", "core", S("Flooding", 73, "Never attempt to drive across a flooded roadway.")),

    Q("q-wx-006", "bad-weather", "Flooding", "c-flood-depth",
      "How much water can float some smaller vehicles?",
      ["As little as six inches", "About three feet", "About two feet", "At least four feet"],
      0,
      "The handbook says as little as six inches of water can float some smaller vehicles, while two feet will carry most away. Once a vehicle floats into deeper water it may roll while filling, trapping everyone inside.",
      "direct", "moderate", S("Flooding", 73,
                              "As little as six (6) inches of water can float some smaller vehicles, while two")),

    Q("q-wx-007", "bad-weather", "Flooding", "c-flood-depth",
      "Which statement about flooded roadways is NOT correct?",
      ["Two feet of water is safe to cross in a full-size vehicle",
       "Six inches of water can float some smaller vehicles",
       "Flooded roads are especially dangerous at night",
       "The road surface may have washed away beneath the water"],
      0,
      "Two feet of water will carry most vehicles away, according to the handbook — it is the opposite of safe. The other three statements are all made in the handbook, including that flooded roadways are especially dangerous at night when depth is much harder to judge.",
      "negative", "tricky", S("Flooding", 73,
                              "(2) feet of water will carry most away.")),

    Q("q-wx-008", "bad-weather", "Ice and snow", "c-ice-brake",
      "How should you brake on ice or packed snow?",
      ["Gently and smoothly, releasing at the first hint the wheels are slipping",
       "Firmly and quickly to shorten the stop",
       "By pulling the parking brake",
       "By downshifting only, never using the brake pedal"],
      0,
      "The handbook says to always apply the brakes gently and smoothly on ice or packed snow, and to release them at the first hint the wheels are slipping. Locked wheels on ice mean no steering and no meaningful braking.",
      "direct", "core", S("Snow and Ice", 74, "always apply the brakes gently and smoothly.")),

    Q("q-wx-009", "bad-weather", "Ice and snow", "c-abs",
      "What is the difference between braking with and without anti-lock brakes?",
      ["With ABS you keep the ability to steer while braking; without it you must pump the brakes to steer",
       "Without ABS you keep steering; with ABS you cannot steer",
       "ABS shortens stopping distance on ice but removes steering",
       "There is no practical difference on ice"],
      0,
      "The handbook states that in a vehicle equipped with anti-lock brakes you maintain the ability to steer while braking, but in a vehicle without them you cannot steer unless you pump the brakes, applying and releasing several times until the vehicle is under control.",
      "application", "tricky", S("Snow and Ice", 74,
                                 "In a vehicle equipped with anti-lock brakes, you maintain the ability to steer while braking.")),

    Q("q-wx-010", "bad-weather", "Fog", "c-fog",
      "Which headlights should you use in fog or dense smoke?",
      ["Low beams", "High beams", "Parking lights only", "Hazard lights instead of headlights"],
      0,
      "The handbook says to use your low-beam headlights in fog or dense smoke, along with reducing speed, staying alert for an emergency stop, and using wipers to clear moisture. High beams reflect off fog back towards you and make seeing worse.",
      "direct", "core", S("Fog and Smoke", 74, "Use your low-beam headlights.")),

    Q("q-wx-011", "bad-weather", "Fog", "c-fog",
      "Fog becomes too thick to see safely and you pull off the road. What else does the handbook say to do?",
      ["Leave your lights on and turn on your hazard lights",
       "Turn all lights off to avoid attracting other drivers",
       "Leave only the interior light on",
       "Keep driving slowly rather than stopping"],
      0,
      "The handbook says that if fog or smoke impairs your vision you should pull off to the side of the road and stop, leave your lights on, and also turn your hazard lights on — so that a vehicle still moving in the fog can see where you are.",
      "scenario", "moderate", S("Fog and Smoke", 74,
                                "leave your lights on and also")),

    Q("q-vc-001", "vehicle-driver-condition", "Inspection", "c-inspection",
      "How often does West Virginia require a vehicle safety inspection?",
      ["Every two years", "Every year", "Every six months", "Only when the vehicle is sold"],
      0,
      "The handbook states West Virginia requires an inspection of all vehicles every two years to ensure they are in safe driving condition. When the vehicle passes, a sticker showing the month and year of the next inspection goes on the windshield.",
      "direct", "core", S("Vehicle Conditions (State Inspection Law)", 74, "West Virginia requires an")),

    Q("q-vc-002", "vehicle-driver-condition", "Inspection", "c-inspection",
      "What does the inspection sticker on your windshield show, and may you remove it?",
      ["The month and year of your next inspection, and removing it is against the law",
       "The date of the last inspection, and it may be removed once expired",
       "The inspection station's number, and it may be moved to another vehicle",
       "Nothing of legal significance; it is advisory only"],
      0,
      "The sticker shows the month and year for your next inspection, and the handbook states plainly that it is against the law for you to remove it. Inspections must be done at a station displaying an official state inspection station sign.",
      "application", "moderate", S("Vehicle Conditions (State Inspection Law)", 74,
                                   "It is against the law for you to remove this sticker.")),

    Q("q-vc-003", "vehicle-driver-condition", "Defects", "c-defects",
      "Which of these does the handbook list as a common vehicle defect that causes crashes?",
      ["Unusable seat belts", "Worn upholstery", "A dirty engine bay", "A missing spare key"],
      0,
      "The handbook's list is faulty tires, brakes, lights, windshield wipers, defrosters, mufflers and exhaust system, horn, mirrors, and unusable seat belts. All are things that affect control, visibility, warning others, or protection in a crash.",
      "direct", "moderate", S("Vehicle Conditions (State Inspection Law)", 75,
                              "Common vehicle defects that cause crashes are faulty tires, brakes, lights, windshield wipers, defrosters")),

    Q("q-vc-004", "vehicle-driver-condition", "Fatigue", "c-fatigue-break",
      "On a long trip, what rest schedule does the handbook recommend?",
      ["A 10-minute break at least every two hours, spent outside the vehicle",
       "A 30-minute break every four hours",
       "A 5-minute break every hour, taken in the vehicle",
       "No break is needed if you feel alert"],
      0,
      "The handbook recommends a 10-minute rest break at least every two hours on a long trip, and specifies it should be spent outside the vehicle — walking around, getting a drink — rather than just sitting still.",
      "direct", "core", S("Fatigue", 75, "take a 10-minute rest break at least every two (2) hours.")),

    Q("q-vc-005", "vehicle-driver-condition", "Fatigue", "c-fatigue-effect",
      "What does the handbook say fatigue does to a driver?",
      ["Dulls your mind and slows your reaction time",
       "Affects vision but not reaction time",
       "Makes you cautious, which compensates for the tiredness",
       "Has no measurable effect below eight hours of driving"],
      0,
      "The handbook says being tired dulls your mind and slows your reaction time. If you are alone and become tired you should pull off the road and rest; if another licensed driver is available you should change drivers as soon as one becomes tired.",
      "direct", "moderate", S("Fatigue", 75, "Being tired dulls your mind and slows your reaction time.")),

    Q("q-vc-006", "vehicle-driver-condition", "Emotions", "c-emotions",
      "You have just had a furious argument and need to drive. What does the handbook advise?",
      ["Gain self control over the emotion before driving",
       "Drive, since concentration improves when emotions are high",
       "Drive but keep to quieter roads",
       "Emotional state is not treated as a driving condition"],
      0,
      "The handbook lists emotional state alongside fatigue, alcohol and defective eyesight or hearing as driver conditions affecting safe operation, and says you should attempt to control emotions such as anger, worry or fear and gain self control before driving.",
      "scenario", "moderate", S("Emotional States", 75,
                                "control these emotions and gain self control before driving.")),

    Q("q-ts-001", "traffic-situations", "Vehicle ahead", "c-following-ahead",
      "What should you always assume about the vehicle ahead of you?",
      ["That it may stop suddenly and without warning",
       "That it will signal before any manoeuvre",
       "That it will maintain a steady speed",
       "That its brake lights are working"],
      0,
      "The handbook says you must always be aware that the vehicle ahead may stop suddenly and without warning, and that if you have not allowed enough following distance the result may be a crash. The defence is to stay alert and keep a safe following distance.",
      "direct", "core", S("Traffic Situations", 76,
                          "the vehicle ahead of you may stop suddenly and without")),

    Q("q-ts-002", "traffic-situations", "Being passed", "c-being-passed",
      "Another driver begins to pass you on a two-lane road. What does the handbook recommend?",
      ["Slow down and keep as close to the right side of the road as possible",
       "Maintain your speed so the pass is predictable",
       "Speed up to shorten the manoeuvre",
       "Move towards the centre line to make your position clear"],
      0,
      "The handbook says not to view being passed as a challenge, and to check your mirror frequently, know what is going on around you, slow down, and keep as close to the right side of the road as possible to make it easier for the other vehicle to pass. Many sideswipe and run-off-road crashes result from being passed.",
      "scenario", "core", S("Traffic Situations", 76,
                            "slow down, and keep as close to the right side of the road as possible, making")),

    Q("q-ts-003", "traffic-situations", "Passing", "c-passing-speed",
      "Is it legal to exceed the speed limit in order to complete a pass?",
      ["No — exceeding the speed limit when passing is illegal",
       "Yes, briefly, while alongside the other vehicle",
       "Yes, if the other vehicle is travelling below the limit",
       "Yes, on two-lane roads only"],
      0,
      "The handbook is explicit that exceeding the speed limit when passing is illegal, and adds a useful test: if you have to speed to pass, you probably do not need to pass. There is no allowance for briefly exceeding the limit to overtake.",
      "direct", "core", S("Traffic Situations", 76, "Exceeding the speed limit when passing is")),

    Q("q-ts-004", "traffic-situations", "Passing", "c-passing-speed",
      "You are behind a vehicle doing just under the limit and could only pass by exceeding it. What does the handbook suggest?",
      ["You probably do not need to pass",
       "Pass anyway, as maintaining flow is the priority",
       "Pass on the right instead",
       "Sound your horn to encourage them to speed up"],
      0,
      "The handbook's own words are that if you have to speed to pass, you probably do not need to pass. It also notes that passing increases wear and fuel consumption and exposes you to head-on, sideswipe and run-off-road crashes, so a marginal pass is rarely worth it.",
      "application", "moderate", S("Traffic Situations", 76,
                                   "If you have to speed to pass, you probably do not need to pass.")),
]

# A second form for every concept that would otherwise be testable one way only.
# A single question per concept can be answered from memory of that question; the
# validator warns about it, and these clear the warning honestly rather than by
# relaxing the check.
questions += [
    Q("q-vh-006b", "driving-habits", "Signalling", "c-tailgater",
      "Which describes your duty toward a vehicle tailgating you?",
      ["Signal whenever you change your driving pattern, since sudden slowing affects them most",
       "Brake sharply to discourage them from following closely",
       "Speed up to open a gap regardless of the limit",
       "You owe no duty to a driver who chooses to follow too closely"],
      0,
      "The handbook treats a tailgating vehicle as one of the six crash situations and puts a responsibility on you: signal whenever you make a change in your driving pattern. Brake-checking a tailgater creates the collision you are trying to avoid.",
      "reversed", "moderate", S("Traffic Situations", 76,
                                "The tailgating vehicle behind you is another situation that may cause a crash.")),

    Q("q-vh-007b", "driving-habits", "Stopping", "c-complete-stop",
      "Which statement about stopping at a stop sign is NOT correct?",
      ["A rolling stop is acceptable when there is no cross traffic",
       "A complete stop is required regardless of traffic",
       "A complete stop is required even when turning right",
       "Pressure from following vehicles may tempt you to only slow down"],
      0,
      "The handbook requires a complete stop regardless of traffic, including when turning right, and specifically warns that the absence of cross traffic and pressure from behind may tempt a driver to merely slow. That temptation is named as impatience.",
      "negative", "moderate", S("Impatience", 71, "even when making a right turn.")),

    Q("q-vh-008b", "driving-habits", "Concentration", "c-concentration",
      "What does the handbook say lack of concentration can result in?",
      ["Failure to be observant enough to avoid a crash",
       "A citation for careless driving",
       "Increased fuel consumption",
       "Slower reaction only in heavy traffic"],
      0,
      "The handbook states that lack of concentration can result in a driver's failure to be observant enough to avoid a crash. It calls concentration one of the most important elements of safe driving.",
      "scenario", "moderate", S("Concentration", 72,
                                "of concentration can result in a driver's failure to be observant enough to avoid a crash.")),

    Q("q-lt-002b", "light-and-night", "Dimming", "c-dim-following",
      "You are following a car at night on a dark road and close to within 150 feet. What must you do?",
      ["Dim your headlights — the rule is within 200 feet when following",
       "Keep high beams on, as the rule applies only to oncoming vehicles",
       "Dim only once you are within 100 feet",
       "Flash your high beams to signal your presence"],
      0,
      "The following rule is 200 feet, so at 150 feet you are already required to dim. High beams from behind reflect off the leading driver's mirrors directly into their eyes, which is why the rule covers following as well as meeting.",
      "application", "tricky", S("Light Conditions", 72,
                                 "When following  another vehicle, dim your headlights within 200 feet of the")),

    Q("q-lt-006b", "light-and-night", "Glare", "c-glare",
      "What does looking directly into oncoming headlights cause?",
      ["Momentary blindness", "Improved depth perception", "Eye strain but no vision loss",
       "A temporary increase in night vision"],
      0,
      "The handbook says looking directly into oncoming headlights causes momentary blindness. That is why the instruction is to look well ahead at the right edge of the road instead, keeping a visual reference while the other vehicle passes.",
      "direct", "core", S("Light Conditions", 72,
                          "Looking directly into oncoming headlights causes momentary blindness.")),

    Q("q-lt-007b", "light-and-night", "Headlight law", "c-headlights-law",
      "Besides darkness, when does the handbook say to turn on your headlights?",
      ["Any time visibility may be impaired, such as fog, smoke or extreme cloudiness",
       "Only between sunset and sunrise as defined by law",
       "Only when rain is heavy enough to need wipers",
       "Only when other vehicles have theirs on"],
      0,
      "The handbook says to turn on headlights when it begins to get dark or any time visibility may be impaired, giving fog, smoke and extreme cloudiness as examples. Turning them on a little early helps other drivers see you.",
      "reversed", "moderate", S("Light Conditions", 72,
                                "cloudiness). If you turn on your headlights a little early, you will help other drivers see you.")),

    Q("q-wx-001b", "bad-weather", "Wet pavement", "c-wet-start",
      "What two effects does the handbook attribute to wet pavement?",
      ["Harder to keep contact with the road on curves, and increased stopping distance",
       "Reduced tire wear and quieter running",
       "Better grip once tires warm up",
       "No effect provided speed is under 45 mph"],
      0,
      "The handbook says the slippery film at the start of a light rain makes it harder to keep in contact with the road on curves and increases stopping distance, and tells you to reduce speed to adjust to these conditions.",
      "application", "moderate", S("Rain", 73,
                                   "you to keep in contact with the road on curves and increases stopping distance.")),

    Q("q-wx-004b", "bad-weather", "Hydroplaning", "c-hydroplane-prevent",
      "When does the handbook say tires should be replaced to help prevent hydroplaning?",
      ["When tread wear indicators are visible",
       "Every two years regardless of wear",
       "When they are more than half worn",
       "Only when a tire fails inspection"],
      0,
      "The handbook says to replace tires when tread wear indicators are visible, and explains why: tires with deep treads allow water to escape from under the tire and can prevent complete hydroplaning at normal highway speeds.",
      "reversed", "moderate", S("Hydroplaning", 73, "Replace tires when tread wear indicators are visible.")),

    Q("q-wx-005b", "bad-weather", "Flooding", "c-flood-never",
      "Why does the handbook say flooded roads are especially dangerous at night?",
      ["It is much more difficult to judge the situation in the dark",
       "Water freezes more readily after dark",
       "Emergency services do not operate at night",
       "Headlights cause water to appear shallower than it is"],
      0,
      "The handbook notes flooded roadways are especially dangerous at night when it is much more difficult to see. Combined with the fact that the road surface may already have eroded away beneath the water, this is why the instruction is never to attempt a crossing.",
      "direct", "moderate", S("Flooding", 73,
                                "Flooded roadways are especially dangerous at night when it is much more difficult to")),

    Q("q-wx-008b", "bad-weather", "Ice and snow", "c-ice-brake",
      "How should you start off on snow or ice?",
      ["Keep engine speed low and accelerate slowly and smoothly",
       "Use high engine speed to break traction free",
       "Start in the highest available gear at full throttle",
       "Accelerate hard briefly, then lift off"],
      0,
      "The handbook says to keep your engine speed low when starting on snow or ice and to accelerate slowly and smoothly, letting the clutch out slowly in a manual. It then suggests testing the brakes while driving slowly to judge how slippery the road is.",
      "application", "moderate", S("Snow and Ice", 74,
                              "When starting on snow or ice, keep your engine speed low.")),

    Q("q-wx-009b", "bad-weather", "Ice and snow", "c-abs",
      "Your vehicle has no anti-lock brakes and you need to steer while braking on ice. What must you do?",
      ["Pump the brakes, applying and releasing until the vehicle is under control",
       "Hold the brake pedal down firmly and steer",
       "Use the parking brake to steer",
       "Steering while braking is impossible in any vehicle"],
      0,
      "Without ABS the handbook says you cannot steer unless you pump the brakes, applying and releasing them several times until you have the vehicle under complete control. Locked wheels cannot steer, which is exactly what ABS does automatically.",
      "scenario", "tricky", S("Snow and Ice", 74,
                              "a vehicle without anti-lock brakes you cannot steer unless you pump the brakes")),

    Q("q-vc-003b", "vehicle-driver-condition", "Defects", "c-defects",
      "Whose responsibility is it to keep a vehicle in proper driving condition between inspections?",
      ["The driver's — the handbook says it is up to you",
       "The inspection station's, until the sticker expires",
       "The DMV's, through random roadside checks",
       "The insurer's, as a condition of coverage"],
      0,
      "The handbook says plainly that it is up to you to keep your vehicle in proper driving condition, then lists the common defects that cause crashes. The two-yearly inspection is a minimum check, not a substitute for maintaining the vehicle.",
      "reversed", "moderate", S("Vehicle Conditions (State Inspection Law)", 75,
                                "It is up to you to keep your vehicle in proper driving condition.")),

    Q("q-vc-004b", "vehicle-driver-condition", "Fatigue", "c-fatigue-break",
      "Where does the handbook say a rest break on a long trip should be spent?",
      ["Outside the vehicle — walking around or getting a drink",
       "In the driver's seat with the engine off",
       "Asleep in the vehicle for at least an hour",
       "Anywhere, provided it lasts ten minutes"],
      0,
      "The handbook specifies the break should be spent outside of the vehicle, giving walking around or getting a cup of coffee or a soft drink as examples. Sitting still in the same seat does little to counter the monotony that caused the fatigue.",
      "application", "moderate", S("Fatigue", 75,
                                   "This rest break should be spent outside of the vehicle")),

    Q("q-vc-005b", "vehicle-driver-condition", "Fatigue", "c-fatigue-effect",
      "You are driving alone and become tired, with no other licensed driver available. What does the handbook say to do?",
      ["Pull off the road and rest",
       "Open the window and continue to your destination",
       "Increase speed to arrive sooner",
       "Continue but reduce following distance to stay engaged"],
      0,
      "The handbook says if you are alone and become tired, pull off the road and rest. Measures like rolling the window down or turning the radio on are offered only as ways to reduce the monotony of driving, not as substitutes for stopping when tired.",
      "scenario", "moderate", S("Fatigue", 75, "If you are alone and become tired, pull off the road and rest.")),

    Q("q-vc-006b", "vehicle-driver-condition", "Driver condition", "c-emotions",
      "Which four driver conditions does the handbook name as most commonly affecting safe operation?",
      ["Fatigue, alcohol, emotional state, and defective eyesight or hearing",
       "Age, inexperience, fatigue and weather",
       "Alcohol, drugs, speed and distraction",
       "Eyesight, hearing, reaction time and height"],
      0,
      "The handbook lists exactly these four. Emotional state sitting in the same list as alcohol and fatigue is the point worth remembering — it is treated as a genuine impairment, not a mood.",
      "direct", "moderate", S("Driver Conditions", 75,
                              "affecting the safe operation of a vehicle are fatigue, alcohol, emotional state, and defective eyesight or")),

    Q("q-ts-001b", "traffic-situations", "Vehicle ahead", "c-following-ahead",
      "What is the defence against the vehicle ahead stopping suddenly?",
      ["Stay alert, anticipate the sudden stop, and maintain a safe following distance",
       "Drive in a different lane wherever possible",
       "Keep your hand over the horn",
       "Watch the vehicle's brake lights exclusively"],
      0,
      "The handbook gives all three parts together: stay alert, anticipate that the driver ahead may make a sudden stop, and maintain a safe following distance. Following distance is what converts a sudden stop ahead into a non-event.",
      "application", "core", S("Traffic Situations", 76,
                               "you should stay alert, anticipate that the driver ahead may make a sudden stop and maintain a")),

    Q("q-ts-002b", "traffic-situations", "Being passed", "c-being-passed",
      "What kinds of crash does the handbook say often result from being passed?",
      ["Sideswipe and run-off-the-road crashes",
       "Rear-end crashes only",
       "Head-on crashes only",
       "Rollover crashes"],
      0,
      "The handbook says many sideswipe and run-off-the-road crashes result from being passed, which is why it tells you to check your mirror frequently, slow down and keep well right rather than treating the pass as a challenge.",
      "direct", "moderate", S("Traffic Situations", 76,
                              "Many sideswipe and run-off -the-road crashes result from being passed.")),
]

questions.append(
    Q("q-vh-005b", "driving-habits", "Signalling", "c-signal-always",
      "Failing to signal is described by the handbook as a bad habit related to which fault?",
      ["Laziness", "Arrogance", "Impatience", "Inattention"],
      0,
      "The handbook raises failing to signal under Laziness, as 'another related bad habit' alongside relying on the mirror instead of turning your head. It warns that letting the combination of these habits develop could cause a serious crash.",
      "reversed", "moderate", S("Laziness", 71, "Another related bad habit is failing to signal.")))

bundle = {
    "topics": topics,
    "concepts": [{"id": c[0], "topicId": c[1], "label": c[2], "statement": c[3], "source": c[4]}
                 for c in concepts],
    "lessons": lessons,
    "questions": questions,
    "signs": [],
}
OUT.write_text(json.dumps(bundle, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"wrote {OUT.name}: {len(topics)} topics, {len(concepts)} concepts, "
      f"{len(lessons)} lessons, {len(questions)} questions")
